name: texi_website
description: A new Flutter project.

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #COMMON
  cupertino_icons: ^1.0.5

  #UI
  flutter_widget_from_html_core: ^0.9.0+2

  # TOAST
  fluttertoast: ^8.0.9

  # IMAGE
  cached_network_image: ^3.2.3

  # BASE
  google_fonts: ^4.0.3

  # CONNECTIVITY
  url_launcher: ^6.1.5

  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - assets/



